# Generated by Django 5.1.2 on 2024-10-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], max_length=10)),
            ],
        ),
    ]
